global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # SolviumAI Quiz Bot (Main Application)
  - job_name: "solvium-quiz-bot"
    static_configs:
      - targets: ["quiz-agent:8000"]
    metrics_path: "/metrics"
    scrape_interval: 10s
    scrape_timeout: 5s

  # Nginx Reverse Proxy
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]
    metrics_path: "/nginx_status"
    scrape_interval: 30s
    scrape_timeout: 5s
